### ISSUE TITLE
Gestión para aprobación y observaciones de las visitas a sedes. 

### ISSUE THREAD

**Issue by Stevenhr** [Stevenhr/Interventoria#33]
Se debe crear la función para que el coordinar pueda ver, **aprobar, cancelar, rechazar**  y dar observaciones a la programación de las visitas de los interventores a cargo que han registrado.  

- La visita cuando sea  aprobada y cancelada: El interventor no la podrá modifica la después. 
- La vista cuando este rechazada: El interventor debe ver la observación del coordinador para corregir la visita.

Se creo el siguiente item para desarrollar dicha funcionalidad:
![captura](https://user-images.githubusercontent.com/18744817/27412484-8c988f7e-56ba-11e7-9f70-3a428c261d0c.PNG)

**Comment by Stevenhr** [comment]
Daniel se debe ingresar un filtro por fecha inicial y final, tratamos de evitar que se muestren todas la visitas de un año o dos años cuando se abra esta vista, esto puede ser mucha información que se muestre y sea innecesaria.

![captura](https://user-images.githubusercontent.com/18744817/27844843-eda14144-60ec-11e7-8ad3-dc06446fcf0b.PNG)

**Comment by Stevenhr** [comment]
Daniel no concuerda las tarjetas de notificación con las visitas registradas.

![capturasedes](https://user-images.githubusercontent.com/18744817/27982011-0c2e713c-635d-11e7-8ab8-602c70467583.PNG)

**Comment by daniiprado** [comment]
Aquí ocurre lo mismo que en visitas a bodegas
