### ISSUE TITLE
Crear visita a bodegas

### ISSUE THREAD

**Issue by Stevenhr** [Stevenhr/Interventoria#35]
- Se debe tener la vista para la creación de la **Mis visitas a bodegas** similar a la vista de **Mis visitas a sedes**.  
 
- La tabla para realizar dicha asignación de visita a bodega es la siguiente: vfn_tbl_visita_bodega.
 
- Al interventor le deben salir solo las bodegas asignadas.

**Comment by Stevenhr** [comment]
Al momento de crear un visita a una bodega no me la muestra en en el calendario.

**Comment by daniiprado** [comment]
Corregido
