### ISSUE TITLE
Gestión para aprobación y observaciones de las visitas a bodegas.

### ISSUE THREAD

**Issue by Stevenhr** [Stevenhr/Interventoria#36]
Se debe crear la función para que el coordinador pueda ver, aprobar, cancelar, rechazar y dar observaciones a la programación de las visitas a bodegas de los interventores a cargo que han registrado.

Realizar un filtro por fecha inicial y final. 
La visita cuando sea aprobada y cancelada: El interventor no la podrá modifica la después.
La vista cuando este rechazada: El interventor debe ver la observación del coordinador para corregir la visita.
Se creo el siguiente ítem para desarrollar dicha funcionalidad:
![captura](https://user-images.githubusercontent.com/18744817/27844828-b6726888-60ec-11e7-8bbb-7eee63313aad.PNG)

Es similar a lo realizado en sedes: 

![captura](https://user-images.githubusercontent.com/18744817/27844839-cd046e5c-60ec-11e7-83e5-dd8f02af8e87.PNG)

**Comment by Stevenhr** [comment]
Daniel no concuerda las tarjetas de notificación con las visitas registradas.

![captura](https://user-images.githubusercontent.com/18744817/27981990-b2452a1c-635c-11e7-830d-fe18b9bb5c6c.PNG)

**Comment by Stevenhr** [comment]
Daniel no concuerda las tarjetas de notificación con las visitas registradas.

![captura](https://user-images.githubusercontent.com/18744817/27982006-f34133ee-635c-11e7-9c22-494d2086c942.PNG)

**Comment by daniiprado** [comment]
las tarjetas muestran el total de todo lo que hay en la base de datos, en los tabs se muestran las visitas donde el campo dt_fecha_visita sea mayor a a la fecha actual, es decir, lo que se muestra en las tarjetas y no se muestran abajo es porque la fecha de visita es no es mayor a la fecha actual ya que no tendría sentido mostrar visitas que ya debieron haber pasado

**Comment by Stevenhr** [comment]
Vale dejemos lo así, sin embargo tengo la duda, porque ellos podrían cambiar de estado visitas que ya hallan pasado, porque lo interventores tienen 5 días después de la fecha de la visita para realizar la ejecución.  Osea que podrían haber cambios de estados después de 5 días de haber registrado la visita. 

**Pero igual dejemos lo así por ahora**.
