### ISSUE TITLE
Modificación en la gestión de aprobación de visitas a bodegas y sedes.

### ISSUE THREAD

**Issue by Stevenhr** [Stevenhr/Interventoria#42]
En las vistas de aprobación de visita bodega y sede, se debe poder ver todas visitas sin validación de tiempo, ellos pueden modificar el estado de cualquier visita a si está halla pasado su fecha de registro, o este aprobada, rechazada o cancelada. En cualquier momento se debe poder cambiar el estado. 

![captura](https://user-images.githubusercontent.com/18744817/28098432-d36462cc-667b-11e7-9725-6da63cd3880f.PNG)

Igualmente como van ha hacer muchas visitas al mes, al año, es necesario que no se muestren inmediatamente en la parte de cancelada, rechazada y aprobada las visitas, y vaya antes antes un filtro de fecha inicial y final para así mostrar las visitas.

**Comment by daniiprado** [comment]
Se añadió un tab con los filtros de fecha inicial, final y por estado , sin embargo en las pestañas dejé que se mostraran las visitas mayor igual al día actual para que no se vea vacío.
