### ISSUE TITLE
Cambios basicos

### ISSUE THREAD

**Issue by Stevenhr** [Stevenhr/Interventoria#47]
- Al momento de crear una visita a sedes y bodegas hay un campo que se llama "Lugar de verificación", este campo se debe eliminar, si quiere lo puede dejar como hidden y en el value en sede le coloca sede y al otro bodega.

![captura](https://user-images.githubusercontent.com/18744817/28253580-f1a615d0-6a6a-11e7-9afa-da35366bed68.PNG)

-  **Día administrativo**:  se deben ingresar una opción para registrar un día administrativo, en este día el interventor no realiza visitas, por tal motivo no necesita aprobación, esta fecha solo se debe ver en el calendario de un color diferente. Solo informativo, esto tanto en bodega como en sedes. 

![captura](https://user-images.githubusercontent.com/18744817/28253682-e6a101da-6a6b-11e7-8968-eb570999470f.PNG)

**Comment by daniiprado** [comment]
- Se cambio el campo tipo text de lugar de verificación por hidden tanto para visitas como a sedes.
- Se corrigió el datepicker para que seleccionara la fecha actual.
- Se añadió la funcionalidad del día administrativo con drag and drop.
![dia administrativo](https://user-images.githubusercontent.com/12104660/28401521-1fbc92b0-6ce0-11e7-92a9-88092d41cba1.gif)
