### ISSUE TITLE
Ajustes Visitas Bodegas y Sedes

### ISSUE THREAD

**Issue by Stevenhr** [Stevenhr/Interventoria#50]
- Se debe poder crear la vista el mismo día. Ahora solo puedo crear visitas a partir de mañana. 
- Se debe poder modificar (los interventores) la fecha y hora de las visitas al momento que se rechacen. 
- Se debe ver a parte en el coordinador las visitas que le hagan una observación los interventores.

**Comment by daniiprado** [comment]
- Es extraño porque si me deja crear el mismo día las visitas ya sea dando clic en el día o en el botón añadir visita:

![visita elmismo dia](https://user-images.githubusercontent.com/12104660/28353596-19543bd0-6c22-11e7-8548-6ddbe76b2852.gif)


- La modificación de fecha se puede hacer arrastrando y soltando en cualquier otra fecha del calendario en la pestaña mes:

![cambiar_fecha](https://user-images.githubusercontent.com/12104660/28353533-c7e3ac90-6c21-11e7-9480-8b5932ab2362.gif)

- Al igual que la fecha la hora se puede cambiar haciendo drag and drop en la pestaña día

![cambiar hora](https://user-images.githubusercontent.com/12104660/28353708-914a0124-6c22-11e7-926f-23cfee5dbbec.gif)

**Comment by Stevenhr** [comment]
- Daniel si esta bien, no entendía un poco el funcionamiento, pero veo que si es así, lo único que faltaría seria que al momento de hacer algún cambio a la visitas le salga al coordinador que cambio se realizo. Ejem. Realicé un visita, el coordinador la aprobó, el interventor le solicito que la rechazara para hacer un cambio, se realizo el cambio de la hora, al coordinador le apareció en estado pendiente pero no se sabe que cambio hizo, se debe mostrar el cambio en algún lado, no se si en una observación. 
- 
- Lo que le decía del día actual no se puede crear visitas, es al momento de crearla por el botón **Añadir visita** el datepicker solo me deja crearlas desde el día posterior, se debe habilitar el día actual.

Día actual 19 de julio 2017: 
![captura](https://user-images.githubusercontent.com/18744817/28396727-db9a65d4-6cc2-11e7-858d-81db57b6270e.PNG)

**Comment by daniiprado** [comment]
Corregido lo del datepicker para seleccionar current date
Pendiente lo de las notificaciones de los cambios u observaciones.

**Comment by daniiprado** [comment]
Ok notificaciones
