### ISSUE TITLE
Gestión de mi perfil

### ISSUE THREAD

**Issue by Stevenhr** [Stevenhr/Interventoria#52]
- Se debe crear la opción de modificar mis datos 
![captura](https://user-images.githubusercontent.com/18744817/28494363-bb39003a-6ef1-11e7-8290-9d31ed9b6236.PNG)
(mi perfil), ingresar foto de perfil, cambiar contraseña. 
![captura](https://user-images.githubusercontent.com/18744817/28494356-863c7ca4-6ef1-11e7-9c81-21585a923782.PNG)

**Comment by Stevenhr** [comment]
Daniel han tenido problemas al subir la imagen del perfil, no quedan y bota un error, me enviaron esta imagen. 
![captura](https://user-images.githubusercontent.com/18744817/28760348-f36f7e72-756b-11e7-8d7b-6775034c55f0.PNG)

**Comment by daniiprado** [comment]
Debe ser porque me faltó indicar que hay que ejecutar el comando `php artisan storage:link` para que cree los accesos a la carpeta Storage
