### ISSUE TITLE
Gestor para la aprobación de las visitas en formato calendario.

### ISSUE THREAD

**Issue by Stevenhr** [Stevenhr/Interventoria#54]
Se debe crear un calendario para la aprobación de visitas por interventor esto en la parte de coordinador, no se debe quitar el actual gestor.

**Comment by daniiprado** [comment]
Se modificó la aprobación de visitas a sedes y bodegas y su funcionamiento es el siguiente:

> Filtros:
- Búsqueda por nombre de interventor, sede, número de visita o fecha, oculta y muestra información en el calendario según se seleccione en filtro. Al dar click sobre el número de la visita, por ejemplo `Visita #12 21 Jul, 2017` el calendario se dirigirá automáticamente a la fecha de dicha visita o si se prefiere usar el input date `Ir a una fecha` que también realiza a misma función.

![filtros](https://user-images.githubusercontent.com/12104660/28859998-3a3cf2d4-7720-11e7-83a8-8d522465eeba.gif)

![filtros_2](https://user-images.githubusercontent.com/12104660/28860160-ec319e04-7720-11e7-8fe8-d4dd8287f6be.gif)

> Información de la Visita

- Al dar clic sobre el evento en el calendario se mostrará la información que respecta a la visita y se pueden realizar las operaciones de Aprobar, Rechazar, Cancelar o Comentar con sus respectivas validaciones:
![info](https://user-images.githubusercontent.com/12104660/28860247-60d4cf6a-7721-11e7-8f05-37054cee9f8f.gif)

> Reportes

- Por último el generador de reportes continúa con su misma función de búsquda por rango de fecha y generación de archivo Excel o CSV

![otro](https://user-images.githubusercontent.com/12104660/28860286-99a2a93e-7721-11e7-843a-10ff751160e4.gif)

**Comment by Stevenhr** [comment]
Daniel cuando dejo todas las carpetas sin seleccionar y quiero una sola institución me vuelve a seleccionar todas.

**Comment by daniiprado** [comment]
Se crea e menú `Aprobar visitas sedes/bodega calendario`, se deja el anterior gestos como estaba, lo del filtro, aún continúo buscando la forma de que la selección sea más dinámica con respecto a mostrar y ocultar eventos según se seleccione.
