### ISSUE TITLE
Georeferenciación de rutas por fecha

### ISSUE THREAD

**Issue by Stevenhr** [Stevenhr/Interventoria#63]
Daniel nos solicitan una activad para el coordinador la cual muestre por día en un mapa las visitas que se van a realizar. Ejemplo, en visitas a sedes ellos eligen las sedes que va hacer la visita y le dan una fecha de la visita, ellas quieren elegir una dia y que les muestre en un mapa cuales son la sedes a visitar en ese día, georeferenciado.

**Comment by daniiprado** [comment]
Las sedes al no tener un valor en los campos latitud y longitud se les genera uno de forma aleatoria para situarlo en el mapa.

Se puede presionar el marcador para ver información de la sede, interventor y día y hora de la visita.

Cuenta con los demás controles que trae google.

![map](https://user-images.githubusercontent.com/12104660/31211964-d9c31846-a962-11e7-8e3e-60c434f7c795.gif)
